#!/usr/bin/env bash
# Hot-patch WSL nginx Connection upgrade + reload (no full reinstall).
set -euo pipefail

cat > /etc/nginx/conf.d/sdkwork-connection-upgrade.conf <<'EOF'
# Generated by sdkwork-webserver hotfix
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
EOF

shopt -s nullglob
for conf in /etc/nginx/sites-enabled/sdkwork/*.conf /etc/nginx/sites-available/sdkwork/*.conf; do
  sed -i 's/proxy_set_header Connection "upgrade";/proxy_set_header Connection $connection_upgrade;/g' "${conf}"
done

nginx -t
systemctl reload nginx
echo "nginx reloaded"

curl -sS --noproxy '*' -o /tmp/api80.txt -w 'api-dev:80 %{http_code}\n' http://api-dev.sdkwork.com/healthz || true
echo -n 'body: '; head -c 120 /tmp/api80.txt; echo
