#!/usr/bin/env bash
# Container entrypoint for the standalone gateway image.
set -euo pipefail

CONFIG_ROOT="/etc/sdkwork/webserver"
SECRETS_ROOT="${CONFIG_ROOT}/secrets"
RUNTIME_CONFIG_FILE="${CONFIG_ROOT}/sdkwork-webserver.toml"
GATEWAY_BINARY="/app/bin/sdkwork-api-web-server-standalone-gateway"
SERVICE_USER="sdkwork"

log() {
  echo "[sdkwork-webserver-entrypoint] $*"
}

ensure_directory() {
  install -d -o "${SERVICE_USER}" -g "${SERVICE_USER}" -m 0750 "$1"
}

ensure_secret_file() {
  local name="$1"
  local file="${SECRETS_ROOT}/${name}"
  if [ ! -s "${file}" ]; then
    ensure_directory "${SECRETS_ROOT}"
    openssl rand -hex 32 > "${file}"
    chown "${SERVICE_USER}:${SERVICE_USER}" "${file}"
    chmod 0600 "${file}"
  fi
}

ensure_database_secret() {
  if [ -n "${SDKWORK_DATABASE_PASSWORD_FILE:-}" ]; then
    return 0
  fi
  local file="${SECRETS_ROOT}/database.secret"
  if [ -n "${SDKWORK_DATABASE_PASSWORD:-}" ] && [ ! -s "${file}" ]; then
    ensure_directory "${SECRETS_ROOT}"
    printf '%s' "${SDKWORK_DATABASE_PASSWORD}" > "${file}"
    chmod 0600 "${file}"
    chown "${SERVICE_USER}:${SERVICE_USER}" "${file}"
  fi
}

apply_primary_domain() {
  local domain="${SDKWORK_WEBSERVER_PRIMARY_DOMAIN:-sdkwork.com}"
  local environment="${SDKWORK_WEBSERVER_ENVIRONMENT:-development}"
  local host_prefix="server-dev"
  if [ "${environment}" = "test" ]; then
    host_prefix="server-test"
  elif [ "${environment}" = "production" ]; then
    host_prefix="server"
  fi
  local public_url="http://${host_prefix}.${domain}"
  if [ "${environment}" = "production" ] && [ "${SDKWORK_WEBSERVER_PUBLIC_SCHEME:-http}" = "https" ]; then
    public_url="https://${host_prefix}.${domain}"
  fi
  export SDKWORK_WEBSERVER_APPLICATION_PUBLIC_HTTP_URL="${SDKWORK_WEBSERVER_APPLICATION_PUBLIC_HTTP_URL:-${public_url}}"
  export SDKWORK_WEBSERVER_APPLICATION_APP_HTTP_URL="${SDKWORK_WEBSERVER_APPLICATION_APP_HTTP_URL:-${public_url}}"
  export SDKWORK_WEBSERVER_APPLICATION_BACKEND_HTTP_URL="${SDKWORK_WEBSERVER_APPLICATION_BACKEND_HTTP_URL:-${public_url}}"
  export SDKWORK_CORS_ALLOWED_ORIGINS="${SDKWORK_CORS_ALLOWED_ORIGINS:-${public_url}}"
}

render_runtime_config() {
  local environment="${SDKWORK_WEBSERVER_ENVIRONMENT:-development}"
  local bind="${SDKWORK_WEBSERVER_APPLICATION_PUBLIC_INGRESS_BIND:-0.0.0.0:3800}"
  local public_url="${SDKWORK_WEBSERVER_APPLICATION_PUBLIC_HTTP_URL}"
  local data_plane_bind="${SDKWORK_WEBSERVER_DATA_PLANE_OPERATIONS_BIND:-127.0.0.1:3901}"
  local ingress_port="${bind##*:}"
  local internal_api_url="http://127.0.0.1:${ingress_port}"

  # [database] config only supports password_file (not password).
  # If compose provided SDKWORK_DATABASE_PASSWORD, ensure_database_secret()
  # will write it to /etc/sdkwork/webserver/secrets/database.secret, so we
  # always point TOML at password_file.
  local db_password_field='password_file = "/etc/sdkwork/webserver/secrets/database.secret"'
  if [ -n "${SDKWORK_DATABASE_PASSWORD_FILE:-}" ]; then
    db_password_field="password_file = \"${SDKWORK_DATABASE_PASSWORD_FILE}\""
  fi

  # Build cors_allowed_origins TOML array from comma-separated env var.
  # "http://a.com, http://b.com" -> ["http://a.com", "http://b.com"]
  local cors_origins="${SDKWORK_CORS_ALLOWED_ORIGINS:-${public_url}}"
  local cors_toml_array
  cors_toml_array=$(printf '%s' "${cors_origins}" | tr ',' '\n' \
    | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//' \
    | awk 'NF{printf "\"%s\", ", $0}' | sed 's/, $//')
  cors_toml_array="[${cors_toml_array}]"

  # NOTE: The RuntimeTomlConfig struct uses #[serde(deny_unknown_fields)].
  # Supported top-level sections: profile, ingress, app_roots, deploy, database,
  # secrets, acme, tls, node, region. Redis is NOT a TOML section — it is
  # configured exclusively via SDKWORK_WEBSERVER_REDIS_* environment variables
  # injected directly by Docker Compose.

  ensure_directory "${CONFIG_ROOT}"
  cat > "${RUNTIME_CONFIG_FILE}" <<EOF
# Generated by sdkwork-webserver-entrypoint for container runtime.
[profile]
deployment_profile = "standalone"
environment = "${environment}"
profile_id = "standalone.${environment}"
node_id = 0

[ingress]
bind = "${bind}"
management_expose_allowed = true
data_plane_operations_bind = "${data_plane_bind}"
public_http_url = "${public_url}"
app_http_url = "${public_url}"
backend_http_url = "${public_url}"
cors_allowed_origins = ${cors_toml_array}

[app_roots]
app_root = "/app"
iam_app_root = "/app/share/sdkwork/iam"
drive_app_root = "/app/share/sdkwork/drive"
deploy_app_root = "/app/share/sdkwork/deploy"
web_store_app_root = "/app/share/sdkwork/webstore"
pc_static_root = "/app/share/sdkwork/webserver/web/pc"

[deploy]
deployment_profile = "standalone"
environment = "${environment}"
profile_id = "standalone.${environment}"
use_memory_drive = false
use_memory_content_provider = false
drive_facade_url = "${internal_api_url}"
drive_internal_api_url = "${internal_api_url}"
drive_internal_api_ingress_token_file = "${SECRETS_ROOT}/drive-internal-api-ingress-token"
knowledgebase_internal_api_url = "${internal_api_url}"
knowledgebase_internal_api_ingress_token_file = "${SECRETS_ROOT}/knowledgebase-internal-api-ingress-token"
web_internal_api_url = "${internal_api_url}"
web_internal_api_ingress_token_file = "${SECRETS_ROOT}/web-internal-api-ingress-token"
runtime_assignment_worker_id = "deploy-worker-0"

[database]
engine = "${SDKWORK_DATABASE_ENGINE:-postgresql}"
host = "${SDKWORK_DATABASE_HOST:-127.0.0.1}"
port = ${SDKWORK_DATABASE_PORT:-5432}
name = "${SDKWORK_DATABASE_NAME:-sdkwork_ai_dev}"
schema = "${SDKWORK_DATABASE_SCHEMA:-${SDKWORK_DATABASE_NAME:-sdkwork_ai_dev}}"
schema_fallback_public = ${SDKWORK_DATABASE_SCHEMA_FALLBACK_PUBLIC:-false}
username = "${SDKWORK_DATABASE_USERNAME:-sdkwork_ai_dev}"
${db_password_field}
ssl_mode = "${SDKWORK_DATABASE_SSL_MODE:-disable}"
max_connections = ${SDKWORK_DATABASE_MAX_CONNECTIONS:-10}
auto_migrate = true

[secrets]
encryption_key_file = "${SECRETS_ROOT}/encryption-key"
deploy_encryption_key_file = "${SECRETS_ROOT}/deploy-encryption-key"

[acme]
profile = "${SDKWORK_WEBSERVER_ACME_PROFILE:-staging}"
directory_url = "${SDKWORK_WEBSERVER_ACME_DIRECTORY_URL:-https://acme-staging-v02.api.letsencrypt.org/directory}"
contact_email = "${SDKWORK_WEBSERVER_ACME_CONTACT_EMAIL:-admin@localhost}"
webroot = "${SDKWORK_WEBSERVER_ACME_WEBROOT:-/var/lib/sdkwork/webserver/acme-webroot}"
account_root = "${SDKWORK_WEBSERVER_ACME_ACCOUNT_ROOT:-/var/lib/sdkwork/webserver/acme-accounts}"
renew_before_days = ${SDKWORK_WEBSERVER_CERT_RENEW_BEFORE_DAYS:-30}
worker_id = "${SDKWORK_WEBSERVER_CERT_WORKER_ID:-certificate-worker-0}"
operation_poll_interval_secs = ${SDKWORK_WEBSERVER_CERT_OPERATION_POLL_INTERVAL_SECS:-5}
renew_scan_interval_secs = ${SDKWORK_WEBSERVER_CERT_RENEW_SCAN_INTERVAL_SECS:-3600}

[tls]
material_root = "${SDKWORK_WEBSERVER_TLS_MATERIAL_ROOT:-/var/lib/sdkwork/webserver/tls-materials}"
runtime_snapshot_file = "${SDKWORK_WEBSERVER_TLS_RUNTIME_SNAPSHOT_FILE:-/var/lib/sdkwork/webserver/tls-materials/tls-runtime.json}"
snapshot_alpn = "${SDKWORK_WEBSERVER_TLS_SNAPSHOT_ALPN:-h2,http/1.1}"

[node]
uuid = "${SDKWORK_WEBSERVER_NODE_UUID:-standalone-${environment}-node}"

[region]
region_code = "${SDKWORK_WEBSERVER_REGION_CODE:-cn}"
seed_locale = "${SDKWORK_DATABASE_SEED_LOCALE:-zh-CN}"
EOF
  chown root:"${SERVICE_USER}" "${RUNTIME_CONFIG_FILE}"
  chmod 0640 "${RUNTIME_CONFIG_FILE}"
}

ensure_pc_static_root() {
  local static_root="${SDKWORK_WEBSERVER_PC_STATIC_ROOT:-/app/share/sdkwork/webserver/web/pc}"
  local environment="${SDKWORK_WEBSERVER_ENVIRONMENT:-development}"

  ensure_directory "${static_root}"

  cat > "${static_root}/index.html" <<'EOF'
<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="utf-8"><title>SDKWork Web Server</title></head>
<body><p>SDKWork Web Server standalone gateway</p></body>
</html>
EOF

  cat > "${static_root}/runtime-env.json" <<EOF
{
  "environment": "${environment}",
  "deploymentProfile": "standalone",
  "profileId": "standalone.${environment}",
  "runtimeTarget": "browser",
  "browserOriginMode": "same-origin",
  "appApiBaseUrl": "/",
  "backendApiBaseUrl": "/",
  "driveAppApiBaseUrl": "/",
  "appbaseAppApiBaseUrl": "/"
}
EOF

  chown -R "${SERVICE_USER}:${SERVICE_USER}" "${static_root}"
  chmod 0755 "${static_root}"
  chmod 0644 "${static_root}/index.html" "${static_root}/runtime-env.json"
}

run_as_service_user() {
  if [ "$(id -u)" -eq 0 ]; then
    runuser -u "${SERVICE_USER}" -- "$@"
    return $?
  fi
  "$@"
}

exec_as_service_user() {
  if [ "$(id -u)" -eq 0 ]; then
    exec runuser -u "${SERVICE_USER}" -- "$@"
  fi
  exec "$@"
}

main() {
  if [ ! -x "${GATEWAY_BINARY}" ]; then
    log "gateway binary is missing at ${GATEWAY_BINARY}"
    exit 1
  fi

  apply_primary_domain
  ensure_database_secret
  for secret_name in encryption-key deploy-encryption-key \
    drive-internal-api-ingress-token knowledgebase-internal-api-ingress-token \
    web-internal-api-ingress-token; do
    ensure_secret_file "${secret_name}"
  done

  render_runtime_config
  ensure_pc_static_root

  case "${1:-serve-management}" in
    serve-management)
      log "running database migration"
      run_as_service_user "${GATEWAY_BINARY}" db-migrate
      log "starting management listener on ${SDKWORK_WEBSERVER_APPLICATION_PUBLIC_INGRESS_BIND:-127.0.0.1:3800}"
      exec_as_service_user "${GATEWAY_BINARY}" serve-management
      ;;
    db-migrate)
      exec_as_service_user "${GATEWAY_BINARY}" db-migrate
      ;;
    *)
      exec_as_service_user "${GATEWAY_BINARY}" "$@"
      ;;
  esac
}

main "$@"
