#!/usr/bin/env bash
# Install nginx :80 domain routing for SDKWork Web Server Docker stacks on WSL.
#
# Authority: APP_RUNTIME_TOPOLOGY_NAMING.md §9 (role host server), NGINX_SPEC.md
# site path `/etc/nginx/sites-enabled/sdkwork/<domain>.conf`.
#
# Upstream ports are the Docker host-published ports for each standalone
# environment. Declarative production/cloud nginx lives in
# deployments/webserver/ (SDKWORK_WEBSERVER_SPEC.md); this script only wires
# local WSL operator routing for container stacks.
#
# Usage:
#   sudo bash deployments/docker/scripts/install-wsl-nginx.sh
#   sudo bash deployments/docker/scripts/install-wsl-nginx.sh development test
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SITES_AVAILABLE="/etc/nginx/sites-available"
SITES_ENABLED="/etc/nginx/sites-enabled"
SDKWORK_SITES_AVAILABLE="${SITES_AVAILABLE}/sdkwork"
SDKWORK_SITES_ENABLED="${SITES_ENABLED}/sdkwork"

log() {
  echo "[sdkwork-webserver-nginx] $*"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    log "run as root: sudo bash deployments/docker/scripts/install-wsl-nginx.sh"
    exit 1
  fi
}

# environment -> host port published by docker-compose
port_for() {
  case "$1" in
    development) echo 13800 ;;
    test) echo 18888 ;;
    production) echo 18080 ;;
    *) return 1 ;;
  esac
}

# environment -> registered public-ingress host (topology cloudPublicHosts)
domain_for() {
  case "$1" in
    development) echo server-dev.sdkwork.com ;;
    test) echo server-test.sdkwork.com ;;
    production) echo server.sdkwork.com ;;
    *) return 1 ;;
  esac
}

# environment -> auxiliary app / backend hosts (same upstream for local parity)
aux_domains_for() {
  case "$1" in
    development) echo "server-app-dev.sdkwork.com server-admin-dev.sdkwork.com" ;;
    test) echo "server-app-test.sdkwork.com server-admin-test.sdkwork.com" ;;
    production) echo "server-app.sdkwork.com server-admin.sdkwork.com" ;;
    *) return 1 ;;
  esac
}

write_site() {
  local domain="$1"
  local upstream_port="$2"
  local available="${SDKWORK_SITES_AVAILABLE}/${domain}.conf"
  local enabled="${SDKWORK_SITES_ENABLED}/${domain}.conf"

  cat > "${available}" <<EOF
# Generated by deployments/docker/scripts/install-wsl-nginx.sh
# Local WSL operator site for Docker standalone stacks.
# Canonical production/cloud declarative source: deployments/webserver/
# NGINX_SPEC site path: /etc/nginx/sites-enabled/sdkwork/${domain}.conf

upstream sdkwork_webserver_${domain//./_} {
    server 127.0.0.1:${upstream_port};
    keepalive 16;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    access_log /var/log/nginx/sdkwork-${domain}.access.log;
    error_log /var/log/nginx/sdkwork-${domain}.error.log;

    location / {
        proxy_pass http://sdkwork_webserver_${domain//./_};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Forwarded-Host \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        client_max_body_size 1100m;
    }
}
EOF

  ln -sfn "${available}" "${enabled}"
  log "installed ${enabled} -> 127.0.0.1:${upstream_port}"
}

install_environment() {
  local environment="$1"
  local port domain aux
  port="$(port_for "${environment}")"
  domain="$(domain_for "${environment}")"
  write_site "${domain}" "${port}"
  for aux in $(aux_domains_for "${environment}"); do
    write_site "${aux}" "${port}"
  done
}

remove_legacy_sites() {
  # Retired dual-authority and nickname site files.
  local legacy
  for legacy in \
    sdkwork-webserver-development.conf \
    sdkwork-webserver-test.conf \
    sdkwork-webserver-production.conf \
    server-dev.sdkwork.com.conf \
    server-test.sdkwork.com.conf \
    server.sdkwork.com.conf \
    testserver.sdkwork.com.conf
  do
    rm -f "${SITES_AVAILABLE}/${legacy}" "${SITES_ENABLED}/${legacy}" \
      "${SDKWORK_SITES_AVAILABLE}/${legacy}" "${SDKWORK_SITES_ENABLED}/${legacy}"
  done
}

main() {
  require_root
  if ! command -v nginx >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq nginx
  fi
  install -d -m 0755 "${SITES_AVAILABLE}" "${SITES_ENABLED}" \
    "${SDKWORK_SITES_AVAILABLE}" "${SDKWORK_SITES_ENABLED}"

  remove_legacy_sites

  if [ "$#" -eq 0 ]; then
    set -- development test production
  fi

  for environment in "$@"; do
    install_environment "${environment}"
  done

  if [ -L "${SITES_ENABLED}/default" ] || [ -e "${SITES_ENABLED}/default" ]; then
    rm -f "${SITES_ENABLED}/default"
    log "removed default site"
  fi
  # Ubuntu nginx.conf often includes sites-enabled/default explicitly; keep a
  # harmless empty stub so nginx -t succeeds after removing the default site.
  if grep -q 'sites-enabled/default' /etc/nginx/nginx.conf 2>/dev/null; then
    : > "${SITES_ENABLED}/default"
    log "wrote empty ${SITES_ENABLED}/default stub for nginx.conf include"
  fi

  nginx -t
  systemctl enable nginx >/dev/null 2>&1 || true
  systemctl restart nginx
  log "nginx reloaded; port 80 routes:"
  for environment in "$@"; do
    log "  $(domain_for "${environment}") (+ app/admin) -> 127.0.0.1:$(port_for "${environment}")"
  done
}

main "$@"
