[package]
name = "sdkwork-webserver-edge-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "sdkwork_webserver_edge_runtime"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["process", "fs", "io-util"] }
tracing.workspace = true
rustls.workspace = true

sdkwork-utils-rust.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
