[package]
name = "sdkwork-webserver-database-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "sdkwork_webserver_database_host"

[dependencies]
dotenvy.workspace = true
sdkwork-database-config.workspace = true
sdkwork-database-drift.workspace = true
sdkwork-database-lifecycle.workspace = true
sdkwork-database-spi.workspace = true
sdkwork-database-sqlx.workspace = true

[dev-dependencies]
sqlx.workspace = true
tokio.workspace = true

[lints]
workspace = true
