[package]
name = "sdkwork-api-webserver-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-webserver application HTTP plane."

[lib]
name = "sdkwork_api_webserver_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
async-trait.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
sdkwork-intelligence-webserver-repository-sqlx.workspace = true
sdkwork-intelligence-webserver-service.workspace = true
sdkwork-webserver-contract.workspace = true
sdkwork-webserver-database-host.workspace = true
sdkwork-web-contract.workspace = true
sdkwork-api-deployments-assembly.workspace = true
sdkwork-skills-database-host.workspace = true
sdkwork-mcp-database-host.workspace = true
sdkwork-routes-webserver-app-api.workspace = true
sdkwork-routes-webserver-backend-api.workspace = true
sdkwork-routes-webserver-internal-api.workspace = true
