#!/usr/bin/env node

// SDKWork Web Server Ubuntu (.deb) installer builder.
//
// Packages the standalone server release archive (tar.gz) into a Debian
// package following RUNTIME_DIRECTORY_SPEC.md section 4.1 and
// PACKAGING_SPEC.md section 5.5:
//   binaries -> /usr/lib/sdkwork/webserver/bin/
//   shared assets -> /usr/share/sdkwork/webserver/ (web/{pc,h5,static}, iam, drive, specs, database)
//   examples -> /usr/share/doc/sdkwork/webserver/examples/
//   systemd units -> /usr/lib/systemd/system/
//   runtime config -> /etc/sdkwork/webserver/ (generated by postinst)
//   durable data -> /var/lib/sdkwork/webserver/ (generated by postinst)
//
// Usage:
//   node scripts/webserver-deb.mjs package --environment test|production
//       [--architecture x64|arm64] [--version <semver>] [--skip-pc-build] [--dry-run]
//   node scripts/webserver-deb.mjs validate --environment test|production
//       [--architecture x64|arm64] [--version <semver>]
//
// dpkg-deb runs natively on Linux; on Windows it is invoked through WSL.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { extract as extractTar } from 'tar';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const RELEASE_OUTPUT_ROOT = path.join(REPO_ROOT, 'dist', 'release');
const INSTALLER_OUTPUT_ROOT = path.join(REPO_ROOT, 'dist', 'installers');
// The staging directory must live on a filesystem with real permission bits
// (Linux ext4). On shared/Windows-mounted filesystems (WSL /mnt) the mode
// bits are not preserved; override with SDKWORK_DEB_STAGE_PARENT.
const STAGE_PARENT = process.env.SDKWORK_DEB_STAGE_PARENT
  ? path.resolve(process.env.SDKWORK_DEB_STAGE_PARENT)
  : path.join(REPO_ROOT, '.sdkwork', 'runtime', 'deb-stage');
const DEB_TEMPLATE_ROOT = path.join(REPO_ROOT, 'scripts', 'deb');
const PC_RUNTIME_ENV_SOURCES = Object.freeze({
  test: path.join(
    REPO_ROOT,
    'apps',
    'sdkwork-webserver-pc',
    'etc',
    'browser',
    'runtime-env.standalone.test.json',
  ),
});
const BINARIES = [
  'sdkwork-api-webserver-standalone-gateway',
  'sdkwork-webserver-website-delivery-edge-runtime',
  'sdkwork-web-node-daemon',
  'sdkwork-web-agent',
  'sdkwork-webserver-certificate-worker',
];
const MAX_DEB_BYTES = 768 * 1024 * 1024;
const MAX_MANIFEST_BYTES = 512 * 1024;

const ENVIRONMENTS = Object.freeze({
  test: {
    packageName: 'sdkwork-webserver-test',
    serviceName: 'sdkwork-webserver-test',
    domain: 'server-test.sdkwork.com',
    ingressPort: 8888,
    publicUrl: 'http://server-test.sdkwork.com:8888',
    // Canonical unified workspace PostgreSQL identity (ENVIRONMENT_SPEC section 7.1).
    databaseName: 'sdkwork_ai_test',
    databaseUser: 'sdkwork_ai_test',
    acmeProfile: 'staging',
    acmeDirectoryUrl: 'https://acme-staging-v02.api.letsencrypt.org/directory',
    certificateWorker: false,
    description: 'SDKWork Web Server standalone gateway installer (test environment)',
  },
  production: {
    packageName: 'sdkwork-webserver',
    serviceName: 'sdkwork-webserver',
    domain: 'server.sdkwork.com',
    ingressPort: 8080,
    publicUrl: 'https://server.sdkwork.com',
    // Canonical unified workspace PostgreSQL identity (ENVIRONMENT_SPEC section 7.1).
    databaseName: 'sdkwork_ai_prod',
    databaseUser: 'sdkwork_ai_prod',
    acmeProfile: 'production',
    acmeDirectoryUrl: 'https://acme-v02.api.letsencrypt.org/directory',
    certificateWorker: true,
    description: 'SDKWork Web Server standalone gateway installer (production environment)',
  },
});

const DEBIAN_ARCHITECTURES = Object.freeze({ x64: 'amd64', arm64: 'arm64' });

function appVersion() {
  const manifest = JSON.parse(
    readFileSync(path.join(REPO_ROOT, 'sdkwork.app.config.json'), 'utf8'),
  );
  const version = manifest?.release?.currentVersion;
  if (typeof version !== 'string' || version.length === 0) {
    throw new Error('sdkwork.app.config.json release.currentVersion is missing');
  }
  return version;
}

function parseArgs(argv) {
  const settings = {
    operation: argv[0],
    environment: undefined,
    architecture: 'x64',
    version: appVersion(),
    skipPcBuild: false,
    skipH5Build: false,
    dryRun: false,
    help: false,
  };
  for (let index = 1; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === '--environment') {
      settings.environment = argv[++index];
    } else if (argument === '--architecture') {
      settings.architecture = argv[++index];
    } else if (argument === '--version') {
      settings.version = argv[++index];
    } else if (argument === '--skip-pc-build') {
      settings.skipPcBuild = true;
    } else if (argument === '--skip-h5-build') {
      settings.skipH5Build = true;
    } else if (argument === '--dry-run') {
      settings.dryRun = true;
    } else if (argument === '--help' || argument === '-h') {
      settings.help = true;
    } else {
      throw new Error(`unsupported option: ${argument}`);
    }
  }
  if (settings.help) {
    return settings;
  }
  if (!['package', 'validate'].includes(settings.operation)) {
    throw new Error(`operation must be package or validate, got ${settings.operation}`);
  }
  if (!ENVIRONMENTS[settings.environment]) {
    throw new Error(`--environment must be test or production, got ${settings.environment}`);
  }
  if (!DEBIAN_ARCHITECTURES[settings.architecture]) {
    throw new Error(`--architecture must be x64 or arm64, got ${settings.architecture}`);
  }
  return settings;
}

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd ?? REPO_ROOT,
    encoding: 'utf8',
    env: options.env ?? process.env,
    stdio: options.capture ? 'pipe' : 'inherit',
    timeout: options.timeoutMs ?? 10 * 60 * 1000,
    maxBuffer: 8 * 1024 * 1024,
    windowsHide: true,
  });
  if (result.error || result.status !== 0) {
    const detail = result.error?.message ?? result.stderr?.trim() ?? `exit ${result.status}`;
    throw new Error(`${command} ${args.join(' ')} failed: ${detail}`);
  }
  return result;
}

function archiveBaseName(settings) {
  return (
    `sdkwork-webserver-linux-${settings.architecture}-standalone-server-${settings.version}`
  );
}

function archivePath(settings) {
  return path.join(RELEASE_OUTPUT_ROOT, `${archiveBaseName(settings)}.tar.gz`);
}

function wslPath(windowsPath) {
  const match = windowsPath.match(/^([A-Za-z]):\\(.*)$/);
  if (!match) {
    throw new Error(`cannot convert Windows path to WSL: ${windowsPath}`);
  }
  return `/mnt/${match[1].toLowerCase()}/${match[2].replace(/\\/g, '/')}`;
}

function wslOrNative(filePath) {
  return process.platform === 'win32' ? wslPath(filePath) : filePath;
}

function runDpkgDeb(args, env = {}) {
  if (process.platform === 'win32') {
    const shellArgs = args.map((arg) => (arg.includes(' ') ? `'${arg}'` : arg)).join(' ');
    return run('wsl.exe', ['-d', 'Ubuntu-22.04', '-e', 'bash', '-lc', `dpkg-deb ${shellArgs}`], {
      capture: true,
      env: { ...process.env, ...env },
    });
  }
  return run('dpkg-deb', args, { capture: true, env: { ...process.env, ...env } });
}

function sha256File(filePath) {
  const hash = createHash('sha256');
  hash.update(readFileSync(filePath));
  return hash.digest('hex');
}

function copyTree(source, target) {
  const entries = [];
  const stack = [{ from: source, to: target }];
  while (stack.length > 0) {
    const current = stack.pop();
    const stat = statSync(current.from);
    if (stat.isDirectory()) {
      mkdirSync(current.to, { recursive: true, mode: 0o755 });
      for (const entry of readdirSync(current.from)) {
        stack.push({ from: path.join(current.from, entry), to: path.join(current.to, entry) });
      }
    } else {
      mkdirSync(path.dirname(current.to), { recursive: true, mode: 0o755 });
      writeFileSync(current.to, readFileSync(current.from), { mode: 0o644 });
      entries.push({ path: current.to, bytes: stat.size });
    }
  }
  return entries;
}

function copyTreeIfPresent(source, target, label) {
  if (!existsSync(source)) {
    console.warn(`[sdkwork-webserver-deb] optional tree missing (${label}): ${source}`);
    mkdirSync(target, { recursive: true, mode: 0o755 });
    return [];
  }
  return copyTree(source, target);
}

function renderTemplate(templatePath, values) {
  let text = readFileSync(templatePath, 'utf8');
  for (const [key, value] of Object.entries(values)) {
    text = text.split(`__${key}__`).join(value);
  }
  return text;
}

async function ensureReleaseArchive(settings) {
  const archive = archivePath(settings);
  if (existsSync(archive)) {
    return archive;
  }
  if (process.platform !== 'linux') {
    throw new Error(
      `release archive is missing: ${archive}\n`
        + 'Build it on a Linux runner first: '
        + 'node scripts/webserver-release.mjs package --deployment-profile standalone '
        + `--architecture ${settings.architecture} --version ${settings.version}`,
    );
  }
  const args = [
    'package',
    '--deployment-profile',
    'standalone',
    '--environment',
    settings.environment,
    '--architecture',
    settings.architecture,
    '--version',
    settings.version,
  ];
  if (settings.skipPcBuild) {
    args.push('--skip-pc-build');
  }
  if (settings.skipH5Build) {
    args.push('--skip-h5-build');
  }
  if (settings.dryRun) {
    args.push('--dry-run');
  }
  process.env.SDKWORK_WEBSERVER_ENVIRONMENT = settings.environment;
  process.env.SDKWORK_ENVIRONMENT = settings.environment;
  run(process.execPath, ['scripts/webserver-release.mjs', ...args]);
  if (!existsSync(archive)) {
    throw new Error(`release archive was not produced: ${archive}`);
  }
  return archive;
}

function collectTree(directory, prefix, output) {
  for (const entry of readdirSync(directory)) {
    const full = path.join(directory, entry);
    const stat = statSync(full);
    const relative = `${prefix}${entry}`;
    if (stat.isDirectory()) {
      collectTree(full, `${relative}/`, output);
    } else {
      output.push({ path: relative, bytes: stat.size, sha256: sha256File(full) });
    }
  }
}

async function assembleDebStage(settings) {
  const environment = ENVIRONMENTS[settings.environment];
  const stageContainer = path.join(STAGE_PARENT, `${environment.packageName}-${process.pid}`);
  const stageRoot = path.join(stageContainer, 'deb-root');
  const extractedRoot = path.join(stageContainer, 'archive-root', 'sdkwork-webserver');
  rmSync(stageContainer, { recursive: true, force: true });
  mkdirSync(stageContainer, { recursive: true, mode: 0o700 });

  const archive = await ensureReleaseArchive(settings);
  mkdirSync(path.dirname(extractedRoot), { recursive: true, mode: 0o755 });
  await extractTar({ file: archive, cwd: path.dirname(extractedRoot), strict: true });

  // Deterministic build: reuse the release archive source date epoch so the
  // deb is reproducible and its checksum is stable across rebuilds.
  const packageManifest = JSON.parse(
    readFileSync(path.join(extractedRoot, 'package.manifest.json'), 'utf8'),
  );
  if (!Number.isSafeInteger(packageManifest.sourceDateEpoch) || packageManifest.sourceDateEpoch < 0) {
    throw new Error('release archive package.manifest.json sourceDateEpoch is invalid');
  }
  const sourceDateEpoch = packageManifest.sourceDateEpoch;

  const libRoot = path.join(stageRoot, 'usr', 'lib', 'sdkwork', 'webserver');
  const shareRoot = path.join(stageRoot, 'usr', 'share', 'sdkwork', 'webserver');
  const docRoot = path.join(stageRoot, 'usr', 'share', 'doc', 'sdkwork', 'webserver');
  const unitRoot = path.join(stageRoot, 'usr', 'lib', 'systemd', 'system');

  // 1. Binaries (private immutable runtime assets).
  for (const binary of BINARIES) {
    const source = path.join(extractedRoot, 'bin', binary);
    if (!existsSync(source)) {
      throw new Error(`release archive is missing bin/${binary}`);
    }
    const target = path.join(libRoot, 'bin', binary);
    mkdirSync(path.dirname(target), { recursive: true, mode: 0o755 });
    writeFileSync(target, readFileSync(source), { mode: 0o755 });
    chmodSync(target, 0o755);
  }
  // App identity and content evidence.
  writeFileSync(
    path.join(libRoot, 'sdkwork.app.config.json'),
    readFileSync(path.join(extractedRoot, 'sdkwork.app.config.json')),
    { mode: 0o644 },
  );
  writeFileSync(
    path.join(libRoot, 'package.manifest.json'),
    readFileSync(path.join(extractedRoot, 'package.manifest.json')),
    { mode: 0o644 },
  );

  // 2. Shared read-only assets. The database contract and specs are
  // service-local runtime inputs resolved under SDKWORK_WEBSERVER_APP_ROOT
  // (module layout), so they stay under /usr/lib/sdkwork/webserver. The IAM
  // and Drive module trees are runtime-mutated (registry materialization
  // writes lock files), so they install under the writable data root
  // /var/lib/sdkwork/webserver instead of read-only /usr/share.
  copyTree(path.join(extractedRoot, 'database'), path.join(libRoot, 'database'));
  copyTree(path.join(extractedRoot, 'specs'), path.join(libRoot, 'specs'));
  copyTree(path.join(extractedRoot, 'share', 'sdkwork', 'iam'), path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'iam'));
  copyTree(path.join(extractedRoot, 'share', 'sdkwork', 'drive'), path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'drive'));
  copyTree(path.join(extractedRoot, 'share', 'sdkwork', 'deploy'), path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'deploy'));
  copyTree(path.join(extractedRoot, 'share', 'sdkwork', 'webstore'), path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'webstore'));
  copyTreeIfPresent(
    path.join(extractedRoot, 'share', 'sdkwork', 'skills'),
    path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'skills'),
    'skills',
  );
  copyTreeIfPresent(
    path.join(extractedRoot, 'share', 'sdkwork', 'mcp'),
    path.join(stageRoot, 'var', 'lib', 'sdkwork', 'webserver', 'mcp'),
    'mcp',
  );
  copyTree(
    path.join(extractedRoot, 'share', 'sdkwork', 'webserver-pc'),
    path.join(shareRoot, 'web', 'pc'),
  );
  copyTree(
    path.join(extractedRoot, 'share', 'sdkwork', 'webserver-h5'),
    path.join(shareRoot, 'web', 'h5'),
  );
  copyTree(
    path.join(extractedRoot, 'share', 'sdkwork', 'webserver-static'),
    path.join(shareRoot, 'web', 'static'),
  );
  if (settings.environment === 'test') {
    // The archive PC runtime env is materialized for standalone.production;
    // the test installer overrides it with the test profile.
    const source = PC_RUNTIME_ENV_SOURCES.test;
    if (!existsSync(source)) {
      throw new Error(`test PC runtime env source is missing: ${source}`);
    }
    writeFileSync(
      path.join(shareRoot, 'web', 'pc', 'runtime-env.json'),
      `${JSON.stringify(JSON.parse(readFileSync(source, 'utf8')), null, 2)}\n`,
      { mode: 0o644 },
    );
  }

  // 3. Documentation examples.
  copyTree(path.join(extractedRoot, 'etc', 'examples'), path.join(docRoot, 'examples'));

  // 4. systemd units.
  const unitValues = { ENVIRONMENT: settings.environment };
  mkdirSync(unitRoot, { recursive: true, mode: 0o755 });
  writeFileSync(
    path.join(unitRoot, `${environment.serviceName}.service`),
    renderTemplate(path.join(DEB_TEMPLATE_ROOT, 'sdkwork-webserver.service.template'), unitValues),
    { mode: 0o644 },
  );
  if (environment.certificateWorker) {
    writeFileSync(
      path.join(unitRoot, 'sdkwork-webserver-certificate-worker.service'),
      renderTemplate(
        path.join(DEB_TEMPLATE_ROOT, 'sdkwork-webserver-certificate-worker.service.template'),
        unitValues,
      ),
      { mode: 0o644 },
    );
  }

  // 5. DEBIAN control metadata and maintainer scripts.
  const debArchitecture = DEBIAN_ARCHITECTURES[settings.architecture];
  const conflictingPackage = settings.environment === 'test'
    ? 'sdkwork-webserver'
    : 'sdkwork-webserver-test';
  const control = [
    `Package: ${environment.packageName}`,
    `Version: ${settings.version}`,
    'Section: web',
    'Priority: optional',
    `Architecture: ${debArchitecture}`,
    'Depends: postgresql, ca-certificates, openssl',
    // The two environment installers share the same canonical runtime paths
    // (RUNTIME_DIRECTORY_SPEC application code `webserver`); only one
    // environment can be installed per host. dpkg removes the conflicting
    // package on switch (config/data are preserved until purge).
    `Conflicts: ${conflictingPackage}`,
    'Maintainer: SDKWork <support@sdkwork.com>',
    'Homepage: https://sdkwork.com',
    `Description: ${environment.description}`,
    ' SDKWork standards-aligned HTTP web server control plane and immutable',
    ' static-site/Wiki delivery data plane.',
    ' .',
    ` Installs the standalone gateway on 0.0.0.0:${environment.ingressPort} bound to ${environment.domain} with`,
    ' an auto-initialized PostgreSQL database, systemd service, and runtime',
    ' directories per RUNTIME_DIRECTORY_SPEC section 4.1.',
    '',
  ].join('\n');
  const debianRoot = path.join(stageRoot, 'DEBIAN');
  mkdirSync(debianRoot, { recursive: true, mode: 0o755 });
  writeFileSync(path.join(debianRoot, 'control'), control, { mode: 0o644 });

  const scriptValues = {
    ENVIRONMENT: settings.environment,
    DOMAIN: environment.domain,
    DB_NAME: environment.databaseName,
    DB_USER: environment.databaseUser,
    SERVICE_NAME: environment.serviceName,
    VERSION: settings.version,
    PUBLIC_URL: environment.publicUrl,
    INGRESS_BIND: `0.0.0.0:${environment.ingressPort}`,
    INGRESS_PORT: String(environment.ingressPort),
    INTERNAL_API_URL: `http://127.0.0.1:${environment.ingressPort}`,
    ACME_PROFILE: environment.acmeProfile,
    ACME_DIRECTORY_URL: environment.acmeDirectoryUrl,
  };
  for (const script of ['postinst', 'prerm', 'postrm']) {
    const rendered = renderTemplate(
      path.join(DEB_TEMPLATE_ROOT, `${script}.sh.template`),
      scriptValues,
    );
    const target = path.join(debianRoot, script);
    writeFileSync(target, rendered, { mode: 0o755 });
    chmodSync(target, 0o755);
  }

  // 6. Installer content manifest (PACKAGING_SPEC section 6 format-equivalent).
  const manifestFiles = [];
  collectTree(path.join(stageRoot, 'usr'), 'usr/', manifestFiles);
  const installerManifest = {
    schemaVersion: 1,
    kind: 'sdkwork.installer-manifest',
    package: environment.packageName,
    version: settings.version,
    environment: settings.environment,
    format: 'deb',
    platform: 'linux',
    distribution: 'ubuntu',
    architecture: debArchitecture,
    domain: environment.domain,
    ingressBind: `0.0.0.0:${environment.ingressPort}`,
    sourceArchive: `${archiveBaseName(settings)}.tar.gz`,
    content: manifestFiles.sort((left, right) => (left.path < right.path ? -1 : 1)),
  };
  const manifestText = `${JSON.stringify(installerManifest, null, 2)}\n`;
  if (Buffer.byteLength(manifestText, 'utf8') > MAX_MANIFEST_BYTES) {
    throw new Error('installer manifest exceeds its size bound');
  }
  writeFileSync(path.join(shareRoot, 'install-manifest.json'), manifestText, { mode: 0o644 });

  return { stageRoot, stageContainer, sourceDateEpoch };
}

function buildDeb(settings, stageRoot, sourceDateEpoch) {
  const debArchitecture = DEBIAN_ARCHITECTURES[settings.architecture];
  const environment = ENVIRONMENTS[settings.environment];
  const debFileName = `${environment.packageName}_${settings.version}_${debArchitecture}.deb`;
  const debPath = path.join(INSTALLER_OUTPUT_ROOT, debFileName);
  mkdirSync(INSTALLER_OUTPUT_ROOT, { recursive: true, mode: 0o755 });
  const temporaryDeb = `${debPath}.tmp-${process.pid}`;
  rmSync(temporaryDeb, { force: true });
  try {
    runDpkgDeb(
      ['--build', '--root-owner-group', wslOrNative(stageRoot), wslOrNative(temporaryDeb)],
      { SOURCE_DATE_EPOCH: String(sourceDateEpoch) },
    );
    const stat = statSync(temporaryDeb);
    if (stat.size === 0 || stat.size > MAX_DEB_BYTES) {
      throw new Error(`deb is outside the size bounds: ${stat.size}`);
    }
    rmSync(debPath, { force: true });
    renameSync(temporaryDeb, debPath);
    writeFileSync(
      `${debPath}.sha256`,
      `${sha256File(debPath)}  ${path.basename(debPath)}\n`,
      { mode: 0o644 },
    );
    return debPath;
  } finally {
    rmSync(temporaryDeb, { force: true });
  }
}

const DEBIAN_PACKAGE_IDS = Object.freeze({
  test: 'linux-ubuntu-x64-standalone-test-server-deb',
  production: 'linux-ubuntu-x64-standalone-server-deb',
});

// Keep sdkwork.app.config.json installConfig checksums in sync with the built
// artifact (security.checksumRequired for enabled packages).
function updateAppManifestChecksum(settings, debPath, { skip = false } = {}) {
  if (skip) {
    return;
  }
  const manifestPath = path.join(REPO_ROOT, 'sdkwork.app.config.json');
  const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'));
  const packageId = DEBIAN_PACKAGE_IDS[settings.environment];
  const pkg = manifest?.artifacts?.installConfig?.packages?.find(
    (candidate) => candidate.id === packageId,
  );
  if (!pkg) {
    throw new Error(`sdkwork.app.config.json is missing package ${packageId}`);
  }
  pkg.checksumAlgorithm = 'sha256';
  pkg.checksum = sha256File(debPath);
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, { mode: 0o644 });
  console.log(
    `[sdkwork-webserver-deb] updated app manifest checksum package=${packageId}`,
  );
}

function validateDeb(settings) {
  const debArchitecture = DEBIAN_ARCHITECTURES[settings.architecture];
  const environment = ENVIRONMENTS[settings.environment];
  const debFileName = `${environment.packageName}_${settings.version}_${debArchitecture}.deb`;
  const debPath = path.join(INSTALLER_OUTPUT_ROOT, debFileName);
  if (!existsSync(debPath)) {
    throw new Error(`installer is missing: ${debPath}`);
  }
  const checksumText = readFileSync(`${debPath}.sha256`, 'utf8').trim();
  const checksumMatch = checksumText.match(/^([a-f0-9]{64})  (.+)$/);
  if (!checksumMatch || checksumMatch[2] !== debFileName) {
    throw new Error('installer checksum sidecar is invalid');
  }
  if (sha256File(debPath) !== checksumMatch[1]) {
    throw new Error('installer SHA-256 does not match its sidecar');
  }
  const info = runDpkgDeb(['--info', wslOrNative(debPath)]).stdout;
  if (!info.includes(`Package: ${environment.packageName}`)
    || !info.includes(`Version: ${settings.version}`)
    || !info.includes(`Architecture: ${debArchitecture}`)) {
    throw new Error('installer control metadata does not match the selected environment');
  }
  const contents = runDpkgDeb(['--contents', wslOrNative(debPath)]).stdout;
  const requiredPaths = [
    './usr/lib/sdkwork/webserver/bin/sdkwork-api-webserver-standalone-gateway',
    `./usr/lib/systemd/system/${environment.serviceName}.service`,
    './usr/share/sdkwork/webserver/install-manifest.json',
    './usr/share/sdkwork/webserver/web/pc/index.html',
    './usr/share/sdkwork/webserver/web/h5/index.html',
    './usr/share/sdkwork/webserver/web/static/index.html',
  ];
  for (const required of requiredPaths) {
    if (!contents.includes(required)) {
      throw new Error(`installer is missing required path ${required}`);
    }
  }
  if (environment.certificateWorker
    && !contents.includes('./usr/lib/systemd/system/sdkwork-webserver-certificate-worker.service')) {
    throw new Error('installer is missing the certificate worker unit');
  }
  console.log(
    `[sdkwork-webserver-deb] validated package=${environment.packageName} version=${settings.version} arch=${debArchitecture} bytes=${statSync(debPath).size}`,
  );
  return debPath;
}

async function main() {
  const settings = parseArgs(process.argv.slice(2));
  if (settings.help) {
    console.log(
      'Usage: node scripts/webserver-deb.mjs <package|validate> --environment <test|production> [--architecture <x64|arm64>] [--version <semver>] [--skip-pc-build] [--skip-h5-build] [--dry-run]',
    );
    return;
  }
  console.log(
    `[sdkwork-webserver-deb] operation=${settings.operation} environment=${settings.environment} architecture=${settings.architecture} version=${settings.version}`,
  );
  if (settings.operation === 'package') {
    const { stageRoot, stageContainer, sourceDateEpoch } = await assembleDebStage(settings);
    try {
      const debPath = buildDeb(settings, stageRoot, sourceDateEpoch);
      console.log(`[sdkwork-webserver-deb] wrote ${path.relative(REPO_ROOT, debPath)}`);
      if (!settings.dryRun) {
        validateDeb(settings);
        updateAppManifestChecksum(settings, debPath);
      }
    } finally {
      rmSync(stageContainer, { recursive: true, force: true });
    }
  } else {
    validateDeb(settings);
  }
}

main().catch((error) => {
  process.stderr.write(
    `[sdkwork-webserver-deb] ${error instanceof Error ? error.message : String(error)}\n`,
  );
  process.exitCode = 1;
});
