environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.sdkwork.com", "server-app.sdkwork.com", "server-admin.sdkwork.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.birdcoder.com", "server-app.birdcoder.com", "server-admin.birdcoder.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.dtupay.com", "server-app.dtupay.com", "server-admin.dtupay.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.sdkwork.cn", "server-app.sdkwork.cn", "server-admin.sdkwork.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.birdcoder.cn", "server-app.birdcoder.cn", "server-admin.birdcoder.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.dtupay.cn", "server-app.dtupay.cn", "server-admin.dtupay.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.skubc.com", "server-app.skubc.com", "server-admin.skubc.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.skubc.cn", "server-app.skubc.cn", "server-admin.skubc.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.zowalk.com", "server-app.zowalk.com", "server-admin.zowalk.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.zowalk.cn", "server-app.zowalk.cn", "server-admin.zowalk.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.offer86.com", "server-app.offer86.com", "server-admin.offer86.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.offer86.cn", "server-app.offer86.cn", "server-admin.offer86.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.86offer.com", "server-app.86offer.com", "server-admin.86offer.com"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["server.86offer.cn", "server-app.86offer.cn", "server-admin.86offer.cn"]
include = ["snippets/gateway-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

