specVersion = 1
kind = "sdkwork.webserver.server"
id = "webserver"
description = "sdkwork-webserver web server (application.public-ingress, application.app-http, application.backend-http)"

[nginx]
enabled = true
profile = "http-core-v1"
unknownDirectivePolicy = "error"
strict = true
confFile = "nginx.conf"

[main]
user = "sdkwork"
workerProcesses = "auto"
pid = "/run/sdkwork/webserver/webserver.pid"
errorLog = "/var/log/sdkwork/webserver/webserver/error.log warn"

[main.events]
workerConnections = 1024

[http]
sendfile = true
keepaliveTimeout = 75
clientMaxBodySize = "1100m"
serverTokens = "off"
gzip = true

[[http.upstream]]
name = "gateway"
loadBalancing = "least-connections"
keepalive = 32

